### ISSUE TITLE
Running of test fails - Mockito cannot mock class

### ISSUE THREAD

**Issue by wagenbm** [Book-Microservices-v2/chapter03#6]
Unfortunately, I am stuck already at page 47 of the book. When running ./mvnw test I am getting this error log

`-------------------------------------------------------------------------------
Test set: microservices.book.multiplication.challenge.ChallengeGeneratorServiceTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.037 s <<< FAILURE! - in microservices.book.multiplication.challenge.ChallengeGeneratorServiceTest
generateRandomFactorIsBetweenExpectedLimits  Time elapsed: 0.036 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 
Unable to initialize @Spy annotated field 'random'.

Mockito cannot mock this class: class java.util.Random.

Mockito can only mock non-private & non-final classes, but the root cause of this error might be different.
Please check the full stacktrace to understand what the issue is.
If you're still not sure why you're getting this error, please open an issue on GitHub.

Java               : 17
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 17.0.5+8
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.5+8
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.15.0-56-generic

Underlying exception : java.lang.IllegalStateException: Cannot access annotation property public abstract boolean jdk.internal.util.random.RandomSupport$RandomGeneratorProperties.isStochastic()
Caused by: org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: class java.util.Random.

Mockito can only mock non-private & non-final classes, but the root cause of this error might be different.
Please check the full stacktrace to understand what the issue is.
If you're still not sure why you're getting this error, please open an issue on GitHub.

Java               : 17
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 17.0.5+8
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.5+8
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.15.0-56-generic

Underlying exception : java.lang.IllegalStateException: Cannot access annotation property public abstract boolean jdk.internal.util.random.RandomSupport$RandomGeneratorProperties.isStochastic()
Caused by: java.lang.IllegalStateException: Cannot access annotation property public abstract boolean jdk.internal.util.random.RandomSupport$RandomGeneratorProperties.isStochastic()
Caused by: java.lang.IllegalAccessException: class net.bytebuddy.description.annotation.AnnotationDescription$ForLoadedAnnotation cannot access interface jdk.internal.util.random.RandomSupport$RandomGeneratorProperties (in module java.base) because module java.base does not export jdk.internal.util.random to unnamed module @55a561cf

`
I am not able to solve the issue. Seems to be an incompatibility issue between the Java version and Mockito? Not sure, how to solve this.

Parameters selected in spring initializr:

Spring Boot 3.0.1
Java 17 (also tested with 19)

I saw some hints to add an explicit dependency for Mockito into pom.xml but this actually does not help as it is unclear which version fits to Java 17 or 19 (is there any version which fits?)

**Comment by wagenbm** [comment]
Sorry, I just recognized, that the issue was already addressed and solved. So, I close this one. :)

**Comment by mechero** [comment]
Hi @wagenbm, 

I'm glad you found the solution. In general, please check the [book's extra chapters available online for free](https://thepracticaldeveloper.com/learn-microservices-v2/#books-extra-chapters). They contain upgrades for newer versions of Spring Boot and Java.

I hope you keep enjoying the book and learning new topics! Kind regards,
Moisés
