### ISSUE TITLE
javax.validation cannot be resolved

### ISSUE THREAD

**Issue by wagenbm** [Book-Microservices-v2/chapter03#9]
Dear Moisés,

I had an issue while importing

javax.validation.constraints.*

for the ChallengeAttemptDTO. I found that this solves the issue:

jakarta.validation.constraints.*

Is this already documented somewhere, I do not find anything related to this on your web page.

Many thanks and best regards,
Matthias

**Comment by mechero** [comment]
Hi Matthias,

Yes, this happens after a JDK / Spring Boot upgrade. The package name has been refactored. There isn't any upgrade published on my blog yet, I'm working on that.

Thanks for letting me know!

**Comment by samv7** [comment]
Thanks, this was helpful for version 3.1.2 with Java 17.

Adding a dependency in the pom.xml for javax.validation caused a test case to fail, so this was probably not the way to go.
